FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel

# WORKDIR /workspace
# RUN apt-get update && apt-get install -y git \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# RUN git clone --branch v1.12.0 https://github.com/pytorch/pytorch.git

# WORKDIR /workspace/pytorch
# RUN git submodule sync
# RUN git submodule update --init --recursive
# RUN conda install -y \
#     numpy \
#     scipy \
#     ninja \
#     pyyaml \
#     mkl \
#     mkl-include \
#     setuptools \
#     cmake \
#     cffi \
#     typing

# RUN conda install -c pytorch magma-cuda113

# ENV CMAKE_PREFIX_PATH=/opt/conda/
# RUN python setup.py develop
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && git clone --branch v1.12.0 https://github.com/pytorch/pytorch.git /workspace/pytorch \
    && cd /workspace/pytorch \
    && git submodule sync \
    && git submodule update --init --recursive \
    && conda install -y numpy scipy ninja pyyaml mkl mkl-include setuptools cmake cffi typing \
    && conda install -c pytorch magma-cuda113 \
    && /opt/conda/bin/conda clean -afy \
    && export CMAKE_PREFIX_PATH=/opt/conda/ \
    && python setup.py develop


WORKDIR /workspace
