FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel

WORKDIR /workspace
RUN git clone --branch v1.3.0 https://github.com/pytorch/pytorch.git

WORKDIR /workspace/pytorch
RUN git submodule sync
RUN git submodule update --init --recursive
RUN conda install -y \
    numpy \
    scipy \
    ninja \
    pyyaml \
    mkl \
    mkl-include \
    setuptools \
    cmake \
    cffi \
    typing
RUN conda install -c pytorch magma-cuda101
ENV CMAKE_PREFIX_PATH=/opt/conda/
RUN python setup.py develop

WORKDIR /workspace
