FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel

WORKDIR /workspace
RUN apt-get update && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch v2.3.1 https://github.com/pytorch/pytorch.git

WORKDIR /workspace/pytorch
RUN git submodule sync
RUN git submodule update --init --recursive
RUN conda install -y \
    numpy \
    scipy \
    ninja \
    pyyaml \
    mkl \
    mkl-include \
    setuptools \
    cmake \
    cffi \
    typing

RUN conda install -c pytorch magma-cuda117

ENV CMAKE_PREFIX_PATH=/opt/conda/
RUN python setup.py develop


WORKDIR /workspace
